### ISSUE TITLE
Allow SSL CA configuration to be a full path

### ISSUE THREAD

**Issue by process0** [strongloop-community/loopback-connector-elastic-search#101]
Currently this module will attempt to load the SSL CA defined in the configuration file relative to this module's path, even if a full path is given.  Allowing full paths will make the configuration settings cleaner and well defined.

**Comment by pulkitsinghal** [comment]
Oh! Can't believe I missed this. Thanks for filing @icenetz
I think your point is valid.
Can you or anyone in your team contribute a PR with tests for this feature request?

**Comment by bharathkontham** [comment]
This is handled in latest versions.
