### ISSUE TITLE
esv6 automatically create index if not exists

### ISSUE THREAD

**Issue by prateekrastogi** [strongloop-community/loopback-connector-elastic-search#110]
Hi,
@bharathkontham I was using esv6 connector, and while creating and deleting indexes frequently in dev environment, I found that we need to create index manually if it doesn't exists yet. In the older version of connector, this issue has already been fixed. It would be nice to be to support such functionality in esv6 version too for avoiding un-necessary manual hack.
Thanks.

**Comment by bharathkontham** [comment]
Use version 1.0.2 https://www.npmjs.com/package/loopback-connector-esv6

**Comment by pulkitsinghal** [comment]
way to go @bharathkontham

**Comment by prateekrastogi** [comment]
@bharathkontham Thanks a lot. Just a minor remark that model's 'replaceOrCreate' is not working as per as the specs of PersistedModel api. Although, I managed to workaround using 'upsert' method.
