### ISSUE TITLE
Missing function destroyAll() ?

### ISSUE THREAD

**Issue by JuergenSimon** [strongloop-community/loopback-connector-elastic-search#124]
Hello,

I am using the `loopback-connector-esv7` and followed the instructions here: https://www.npmjs.com/package/loopback-connector-esv7

In my code, I'm using the `destroyAll()` method on some entities. Unfortunately I am getting the following error message after switching to `loopback-connector-esv7`:

```
(node:7797) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: destroyAll() must be implemented by the connector
```

How do I fix this?

**Comment by bharathkontham** [comment]
@JuergenSimon connector-es is deprecated. I've updated [loopback-connector-esv6](https://www.npmjs.com/package/loopback-connector-esv6) `@2.0.0` plugin to support both Elastic version 6 and 7.
Same code merged in master branch of this repository, please check updated README and examples/server/datasources.json file for sample.

destroyAll is working as expected in this version.

**Comment by true-eye** [comment]
@bharathkontham Right now, the doc says `This connector will only connect to one index per datasource.`
My project has two indexes for mappings originally. How should I configure it?
