### ISSUE TITLE
Automigrate when index or type does not exist yet

### ISSUE THREAD

**Issue by fabien** [strongloop-community/loopback-connector-elastic-search#20]
Perhaps it's because I'm running an older ES version (1.2.1), but it seems that without any proper pre-checks and handling (`indices.delete` and `indices.existsType`), you're unable to run automigration in order to create a new index from scratch. @pulkitsinghal is this correct?

Here's my current monkey-patched solution:

```
var automigrate = dataSource.connector.automigrate;
dataSource.connector.automigrate = function(models, cb) {
    var self = this;
    var params = { index: self.settings.index };
    this.db.indices.delete(params, function(err, info) {
        if (err && err.message.indexOf('IndexMissingException') === -1) return cb(err);
        self.db.indices.create(params, function(err, info) {
            if (err) return cb(err);
            automigrate.call(self, models, cb);
        });
    });
};

var removeMappings = dataSource.connector.removeMappings;
dataSource.connector.removeMappings = function(modelNames, callback) {
    var self = this;
    var settings = this.settings;
    if (_.isFunction(modelNames)) {
        callback = modelNames;
        modelNames = _.pluck(settings.mappings, 'name');
    }
    var mappingsToRemove = _.filter(settings.mappings, function(mapping){
        return !modelNames || _.include(modelNames, mapping.name);
    });
    
    modelNames = _.pluck(mappingsToRemove, 'name');
    
    support.async.filter(modelNames, function(type, next) {
        self.db.indices.existsType({ index: settings.index, type: type }, next);
    }, function(filtered) {
        removeMappings.call(self, filtered, callback);
    });
};

```

**Comment by pulkitsinghal** [comment]
How about submitting a PR?

**Comment by pulkitsinghal** [comment]
@fabien - I was re-reviewing this and I had a few questions:

1. What you did for the tests [here](https://github.com/fabien/loopback-connector-elastic-search/commit/2c5c375fb9eacdcb3f97b40c885b78873b4ae639#diff-2188140f8e1212974a697c3da77d751aR33):

  ```
  {
    elasticsearch: {
      type: 'Customer' // could set override here
  }
  ```
  Can the same thing be accomplished within a model's JSON file by setting [datasource-specific options](https://docs.strongloop.com/display/public/LB/Model+definition+JSON+file#ModeldefinitionJSONfile-Datasource-specificoptions)?

2. You named it `elasticsearch` by default in the testcase. But would I be correct to state that the value of this key must match the value of the corresponding connector property in `datasources.json`?
