### ISSUE TITLE
Unable to define _id_, _parent_ or other top level mapping attributes

### ISSUE THREAD

**Issue by mrfelton** [strongloop-community/loopback-connector-elastic-search#22]
The only thing that gets passed through to ES is `properties` and it's currently impossible to define `_id_`, `_parent_` or other top level mapping attributes.

**Comment by pulkitsinghal** [comment]
Just to be sure that I found the right references:

1. version `0.90`
  * https://www.elastic.co/guide/en/elasticsearch/reference/0.90/mapping-id-field.html
  * https://www.elastic.co/guide/en/elasticsearch/reference/0.90/mapping-parent-field.html
2. version `1.6`
  * https://www.elastic.co/guide/en/elasticsearch/reference/1.6/mapping-id-field.html
  * https://www.elastic.co/guide/en/elasticsearch/reference/1.6/mapping-parent-field.html

These are what you're referring to correct?

**Comment by mrfelton** [comment]
Hi @pulkitsinghal 
Yes, those are the specific ones that I was referring to. However, I think it should really be made possible to set all mapping values through the datasources schema file rather than limiting it to specific ones.

I've been playing around with this, which seems to do the job in my limited testing:
https://gist.github.com/mrfelton/c28f6c54735628b20f81

**Comment by pulkitsinghal** [comment]
If you've got the spare time to contribute, I would gladly accept a PR! Let me know.
