### ISSUE TITLE
How to stop the message "will sort on loopback specified IDs"?

### ISSUE THREAD

**Issue by sanori** [strongloop-community/loopback-connector-elastic-search#40]
I just attach loopback-connector-es to my loopback implementation.
But the loopback server says "will sort on loopback specified IDs" for each DB connection

It seems that the message from https://github.com/strongloop-community/loopback-connector-elastic-search/blob/master/lib/esConnector.js#L433 .
I guess I can stop the messages by setting the creteria.order. But how?

Does anyone know about this?

**Comment by pulkitsinghal** [comment]
You just want to stop the log messages correct?

**Comment by sanori** [comment]
If I do it wrong, I want to fix it.
If I do it correct, I want to stop the bogus message.

**Comment by pulkitsinghal** [comment]
Would you like to submit a PR to remove the log message? Otherwise I can do so and release a new version.

**Comment by pulkitsinghal** [comment]
@sanori - feel free to use version `1.0.5` logs are gone
