### ISSUE TITLE
datasources.json location in sample app project?

### ISSUE THREAD

**Issue by harshadyeola** [strongloop-community/loopback-connector-elastic-search#41]
Where I should keep my `datasources.json` file for my app. When I refer README/doc I find it in `example/server/datasources.json`
So when I install this module with `npm install`  the source goes in `node_modules` directory of my app directory.
So should I edit my `datasources.json` file in `node_modules` of my app?

**Comment by pulkitsinghal** [comment]
1. `examples` directory is not published to NPM so you will not find it under `node_modules` directory of your app after `npm install`
1. You should *not* edit `datasources.json` file in `node_modules`
1. `datasources.json` file for your loopback app should be in your `server` directory:

  ```
  > your app
    > server
      > datasources.json
    > node_modules
  ```
