### ISSUE TITLE
Add a collaborator to this project

### ISSUE THREAD

**Issue by pulkitsinghal** [strongloop-community/loopback-connector-elastic-search#67]
@bajtos and @crandmck - one of my team members will be helping me maintain this repo, going forward. Can you please add @aquid as a collaborator on this project, like myself? I don't have the privileges to do so. Thank You!

If you need some sort of dev history or something, let me know and I'll provide.

@bajtos you may remember @aquid from his contribution to the angular sdk:

`modelsToIgnore option support for generator (Aquid Shahwar)`

https://github.com/strongloop/grunt-loopback-sdk-angular/commit/5d65107dc93009b53875c05302e3f1350ba5c054

**Comment by crandmck** [comment]
@bajtos I can add him as a collaborator, but would it be better to add him to the maintainers group?
I do seem to be able to do that--since you're a project admin, I think you should be able to.

**Comment by bajtos** [comment]
@pulkitsinghal done

@aquid please check your inbox for an invitation to join strongloop-community org on GitHub. 

@crandmck I agree that adding @aquid to the maintainers group is better, @pulkitsinghal is in that group (team) too. I did exactly that.
